### ISSUE TITLE
兵马俑BBS账号注册系统出错

### ISSUE THREAD

**Issue by arcticswallow** [bmybbs/bmybbs#104]
首次输入验证码，系统提示出现故障，请联系站长

再次输入验证码，系统提示没有验证码，请重新提交表单，然后每次都这样循环下去[](url)

**Comment by IronBlood** [comment]
是 www 还是 telnet 方式？

**Comment by arcticswallow** [comment]
www方式

**Comment by IronBlood** [comment]
把最近的一封确认函转发给 bmy[at]xjtu.edu.cn 我看看

**Comment by arcticswallow** [comment]
好的，已发送
